[package]
name = "day5"
version = "0.1.0"
authors = ["Beau Harrison <beau.harrison@unifysolutions.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
